export const ACTIONS = {
  UPDATE_FIELD: "UPDATE_FIELD",
  UPDATE_ERROR: "UPDATE_ERROR",
  FETCH_DATA: "FETCH_DATA",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",
  ADD_COUNTRIES: "ADD_COUNTRIES",
  POST_DATA: "POST_DATA",
  POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
  POST_DATA_FAIL: "POST_DATA_FAIL",
};
